version: '3'

services:
  next-template:
    image: next_template
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - API_DEV=http://localhost:5000/api/v1
    stdin_open: true
    tty: true
    ports:
      - 3000:3000